### ISSUE TITLE
Cash previously held and already collected still displaying in subsequent maintenance session.

### ISSUE THREAD

**Issue by khunshwephyo** [maurzcitrus/vmcsTest#1]
Upon a subsequent re-login to the Maintenance Panel in the same session, the cash previously held and already collected, persists in display. This sometimes causes confusion to Maintainer.

**Comment by kartisuri** [comment]
@Jayendraz  This is a valid bug. Can you please work on this and close asap

**Comment by Jayendraz** [comment]
@kartisuri  Cash clear bug has been resolved.

**Comment by kartisuri** [comment]
@Jayendraz  As a tester please test this bug fix R1.0.8.1

**Comment by Jayendraz** [comment]
@kartisuri It has been tested and working fine. You can close the ticket now.

**Comment by kartisuri** [comment]
@khunshwephyo  This bug has been fixed R1.0.8.1. Can you please close the ticket.

**Comment by khunshwephyo** [comment]
tested okay
